'use client'

import { useEffect, useState, useTransition } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ChevronLeft, Plus, KeyRound, Trash2 } from 'lucide-react'
import { Card } from '@/components/ui/Card'
import { Input } from '@/components/ui/Input'
import { Button } from '@/components/ui/Button'
import { addEmployee, deleteEmployee, toggleEmployee, updateEmployeePin, updateEmployeePermissions } from '@/lib/actions/admin'
import { DEFAULT_EMPLOYEE_PERMISSIONS, type Permission, type PermissionSet } from '@/lib/permissions'

type Employee = { id: string; name: string; is_active: boolean; created_at: string; permissions?: PermissionSet }
const groups: Array<{ title: string; items: Array<[Permission, string]> }> = [
  { title: 'Painel e financeiro', items: [['view_dashboard','Ver painel'],['view_financials','Ver valores financeiros e lucro']] },
  { title: 'Veículos', items: [['view_vehicles','Ver veículos'],['add_vehicles','Adicionar veículos'],['edit_vehicles','Editar veículos'],['delete_vehicles','Excluir veículos'],['view_vehicle_profit','Ver custo e lucro dos veículos'],['manage_documents','Gerenciar documentos']] },
  { title: 'Transações', items: [['view_transactions','Ver transações'],['add_expenses','Adicionar despesas'],['record_sales','Registrar vendas e trocas'],['edit_transactions','Editar transações'],['delete_transactions','Excluir transações']] },
  { title: 'Relatórios', items: [['view_reports','Ver relatórios']] },
]

export default function AdminPage() {
  const router = useRouter(); const [employees,setEmployees]=useState<Employee[]>([]); const [loading,setLoading]=useState(true); const [pending,startTransition]=useTransition()
  const [showAdd,setShowAdd]=useState(false); const [name,setName]=useState(''); const [pin,setPin]=useState(''); const [error,setError]=useState(''); const [addPerms,setAddPerms]=useState<PermissionSet>({...DEFAULT_EMPLOYEE_PERMISSIONS}); const [editing,setEditing]=useState<Employee|null>(null); const [editPerms,setEditPerms]=useState<PermissionSet>({}); const [reset,setReset]=useState<Employee|null>(null); const [newPin,setNewPin]=useState('')
  const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/employees');if(r.status===403){router.push('/inicio');return}const d=await r.json();setEmployees(d.employees??[])}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const toggle=(p:PermissionSet,key:Permission,setter:(p:PermissionSet)=>void)=>setter({...p,[key]:!(p[key]??DEFAULT_EMPLOYEE_PERMISSIONS[key]??false)})
  const PermissionEditor=({value,setValue}:{value:PermissionSet;setValue:(p:PermissionSet)=>void})=><div className="space-y-4">{groups.map(g=><div key={g.title}><p className="text-[12px] font-semibold text-ios-secondary uppercase mb-2">{g.title}</p><div className="space-y-2">{g.items.map(([key,label])=><label key={key} className="flex items-center justify-between gap-3 text-[14px]"><span>{label}</span><input type="checkbox" checked={value[key]??DEFAULT_EMPLOYEE_PERMISSIONS[key]??false} onChange={()=>toggle(value,key,setValue)} className="w-5 h-5" /></label>)}</div></div>)}</div>
  const create=()=>{setError('');if(!name.trim()){setError('Nome obrigatório.');return}if(!/^\d{4}$/.test(pin)){setError('PIN deve ter 4 dígitos.');return}startTransition(async()=>{try{await addEmployee(name,pin,addPerms);setName('');setPin('');setAddPerms({...DEFAULT_EMPLOYEE_PERMISSIONS});setShowAdd(false);await load()}catch(e){setError(e instanceof Error?e.message:'Erro ao adicionar.') }})}
  return <div className="px-4 pt-12 animate-page-enter pb-24"><Link href="/mais" className="flex items-center gap-1 text-[14px] text-ios-secondary mb-5 -ml-1"><ChevronLeft className="w-5 h-5"/>Mais</Link><h1 className="text-[28px] font-bold mb-2">Gerenciar Equipe</h1><p className="text-[13px] text-ios-secondary mb-6">O proprietário sempre tem acesso total. Defina exatamente o que cada funcionário pode ver e alterar.</p>
  {showAdd?<Card className="mb-6 space-y-4"><p className="font-semibold">Novo Funcionário</p><Input label="Nome" value={name} onChange={e=>setName(e.target.value)}/><Input label="PIN (4 dígitos)" type="password" inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))}/><PermissionEditor value={addPerms} setValue={setAddPerms}/>{error&&<p className="text-[12px] text-expense">{error}</p>}<div className="flex gap-2"><Button onClick={create} loading={pending} className="flex-1">Criar usuário</Button><Button onClick={()=>setShowAdd(false)} className="flex-1 bg-ios-fill text-ios-primary">Cancelar</Button></div></Card>:<button onClick={()=>setShowAdd(true)} className="w-full flex justify-center items-center gap-2 py-3 rounded-2xl border-2 border-dashed border-ios-border text-[14px] text-ios-secondary mb-6"><Plus className="w-4 h-4"/>Adicionar Funcionário</button>}
  {loading?<p className="text-sm text-ios-secondary">Carregando...</p>:<div className="space-y-3">{employees.map(emp=><Card key={emp.id}><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{emp.name}</p><p className="text-[11px] text-ios-tertiary">{emp.is_active?'Ativo':'Desativado'}</p></div><div className="flex gap-2"><button onClick={()=>{setEditing(emp);setEditPerms({...DEFAULT_EMPLOYEE_PERMISSIONS,...(emp.permissions??{})})}} className="text-[12px] px-3 py-2 bg-ios-fill rounded-xl">Permissões</button><button onClick={()=>{setReset(emp);setNewPin('')}} className="w-8 h-8 bg-blue-50 rounded-xl flex items-center justify-center"><KeyRound className="w-4 h-4"/></button><button onClick={()=>startTransition(async()=>{await toggleEmployee(emp.id,!emp.is_active);await load()})} className="text-[12px] px-2">{emp.is_active?'Desativar':'Ativar'}</button><button onClick={()=>{if(confirm(`Remover ${emp.name}?`))startTransition(async()=>{await deleteEmployee(emp.id);await load()})}} className="w-8 h-8 bg-red-50 rounded-xl flex items-center justify-center"><Trash2 className="w-4 h-4 text-expense"/></button></div></div></Card>)}</div>}
  {editing&&<div className="fixed inset-0 z-50 bg-black/40 flex items-end" onClick={()=>setEditing(null)}><div className="w-full bg-white rounded-t-3xl p-6 max-h-[85vh] overflow-y-auto space-y-4" onClick={e=>e.stopPropagation()}><p className="text-[17px] font-bold">Permissões — {editing.name}</p><PermissionEditor value={editPerms} setValue={setEditPerms}/><div className="flex gap-2"><Button className="flex-1" loading={pending} onClick={()=>startTransition(async()=>{await updateEmployeePermissions(editing.id,editPerms);setEditing(null);await load()})}>Salvar permissões</Button><Button className="flex-1 bg-ios-fill text-ios-primary" onClick={()=>setEditing(null)}>Cancelar</Button></div><p className="text-[11px] text-ios-tertiary">Alterações entram em vigor no próximo login do funcionário.</p></div></div>}
  {reset&&<div className="fixed inset-0 z-50 bg-black/40 flex items-end" onClick={()=>setReset(null)}><div className="w-full bg-white rounded-t-3xl p-6 space-y-4" onClick={e=>e.stopPropagation()}><p className="font-bold">Redefinir PIN — {reset.name}</p><Input label="Novo PIN" type="password" inputMode="numeric" maxLength={4} value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,'').slice(0,4))}/><Button loading={pending} onClick={()=>{if(!/^\d{4}$/.test(newPin))return;startTransition(async()=>{await updateEmployeePin(reset.id,newPin);setReset(null)})}}>Salvar</Button></div></div>}
  </div>
}
